[project]
name = "tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "malaya-speech>=1.3.0.2",
    "pyaudio>=0.2.14",
]
